### ISSUE TITLE
How to farm with more then one preset?

### ISSUE THREAD

**Issue by undeadrex** [TWOverflow/FarmOverflow#16]
in your settings, it's stated that it's able to use more then 1 preset to farm... i've been wondering for so long, how do you farm with 2 different preset?? 
i open 2 tabs in firefox, 1 farm with light calvary, 1 farm with axe man... but it's only sending out 1 preset instead of 2

**Comment by mafrazz** [comment]
Literally create two presets with the exact same name.
On settings, you'll see that theres only one preset available to select from the two you created. The script will considerate those two presets as one.
When the farm is running, the script will try to use the first preset created, if it fails to send, the second used.
